Repository Capstone-Walking/Capstone_FE, pull requests merged in 2024-04, with the labels that each got.

#3 기본 개발 환경 설정
  README.md
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/App.test.js
  src/index.css
  src/index.js
  src/pages/HomePage.jsx
  src/theme.js
Labels: Type: Design, Type: Chore

#10 fix: 레이아웃 수정
  src/App.js
  src/components/Layout.jsx
  src/components/MenuBarLayout.jsx
  src/pages/HomePage/HomePage.jsx
  src/pages/MyPage/MyPage.jsx
Labels: Type: Refactor

#11 feat: + 버튼, 로그인 모달 추가
  package-lock.json
  package.json
  src/assets/icon/kakaoImage.png
  src/components/Layout.jsx
  src/pages/HomePage/HomePage.jsx
  src/pages/HomePage/componenets/Modal.jsx
  src/theme.js
Labels: Type: Feature, Type: Design
